services:
  runner:
    build: .
    environment:
      - ORGANIZATION= *****
      - ACCESS_TOKEN= *****
      - RUNNER_NAME= *****
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
    restart: always
